---
- hosts: targets
  remote_user: nnyimc
  become: True
  name: install jdk8 on debian
  tasks: 
    - name: install wget
      apt:
        name: wget
        update_cache: yes
        state: latest
    - name: add key
      apt_key:
        url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
        state: present
    - name: add repository
      apt_repository:
        repo: "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ bullseye main"
        state: present
    - name: launch apt-get update
      apt:
        update_cache: yes
    - name: install adoptopendjdk-8-hotspot
      apt:
        name: adoptopenjdk-8-hotspot
        state: latest
