---
- hosts: targets
  remote_user: nnyimc
  become: True
  name: Configure LAMP stack on debian
  tasks:
  - name: install firewalld
    apt:
      name: firewalld
      state: present
  - name: start firewalld
    service:
      name: firewalld
      state: started
      enabled: yes
  - name: install mariadb-server
    apt:
      name: mariadb-server
      state: present
  - name: copy my.cnf file
    copy: 
      src: /etc/mysql/my.cnf
      dest: /etc/mysql/my.cnf
      mode: 0644
  - name: start mariadb
    service:
      name: mariadb
      state: started
  - name: update firewall settings
    command: "sudo firewall-cmd --permanent --zone=public  --add-port=3306/tcp"
  - name: reload firewall
    command: "sudo firewall-cmd --reload"
  - name: install python3-PyMySQL
    apt:
      name: python3-pymysql
      state: present
  - name: change the root MySQL credentials
    shell: mysql -u root -p '' -e 'alter user "root"@localhost identified via mysql_native_password using PASSWORD("")'
  - name: remove anonymous users
    mysql_user:
      name: ""
      host_all: yes
      state: absent
  - name: install web server lighttpd
    apt:
      name: lighttpd
      state: present
  - name: start lighttpd service
    service:
      name: lighttpd
      state: started
  - name: update firewall
    command: "sudo firewall-cmd --permanent --zone=public --add-port=80/tcp"
  - name: reload firewall
    command: "sudo firewall-cmd --reload"
